---
- name: Download Hive Checksum
  get_url:
    url: "http://artifactory.corp.atscale.com/ext-packages/hive/{{ hive_download_file }}.md5"
    dest: "{{ download_dir }}/{{ hive_download_file }}.md5"
    force: yes
    mode: 0440

- name: Download Hive
  get_url:
    url: "http://artifactory.corp.atscale.com/ext-packages/hive/{{ hive_download_file }}"
    checksum: "md5:{{ lookup('file', '{{ download_dir }}/{{ hive_download_file }}.md5') }}"
    dest: "{{ download_dir }}/{{ hive_download_file }}"
    timeout: 60
    mode: 0440

- name: Unpack Hive
  unarchive:
    src: "{{ download_dir }}/{{ hive_download_file }}"
    copy: no
    dest: "{{ share_dir }}"

- name: Symlink MySQL connector into Hive lib directory
  file:
    src: /usr/share/java/mysql-connector-java.jar
    dest: "{{ hive_lib_dir }}/mysql-connector-java.jar"
    state: link

- name: Apply Hive config files
  template:
    src: "templates/hive-{{ hive_version }}/conf/{{ item }}.j2"
    dest: "{{ hive_conf_dir }}/{{ item }}"
    owner: hive
    group: hadoop
    mode: 0644
  with_items:
    - hive-site.xml

- name: Chown Hive to hive user
  file:
    path: "{{ hive_home }}"
    state: directory
    owner: hive
    group: hadoop
    recurse: yes
