---
- name: Download Hadoop Checksum
  get_url:
    url: "http://artifactory.corp.atscale.com/ext-packages/hadoop/{{ hadoop_download_file }}.md5"
    dest: "{{ download_dir }}/{{ hadoop_download_file }}.md5"
    force: yes
    mode: 0440

- name: Download Hadoop
  get_url:
    url: "http://artifactory.corp.atscale.com/ext-packages/hadoop/{{ hadoop_download_file }}"
    checksum: "md5:{{ lookup('file', '{{ download_dir }}/{{ hadoop_download_file }}.md5') }}"
    dest: "{{ download_dir }}/{{ hadoop_download_file }}"
    timeout: 60
    mode: 0440

- name: Unpack Hadoop
  unarchive:
    src: "{{ download_dir }}/{{ hadoop_download_file }}"
    copy: no
    dest: "{{ share_dir }}"

- name: Apply Hadoop config files
  template:
    src: "templates/hadoop-{{ hadoop_version }}/etc/hadoop/{{ item }}.j2"
    dest: "{{ hadoop_conf_dir }}/{{ item }}"
    owner: hadoop
    group: hadoop
    mode: 0644
  with_items:
    - core-site.xml
    - hadoop-env.sh
    - hdfs-site.xml
    - mapred-site.xml
    - yarn-site.xml

- name: Create missing Hadoop directories
  file:
    path: "{{ item }}"
    state: directory
    owner: hadoop
    group: hadoop
    mode: 0755
  with_items:
    - "{{ hadoop_home }}/logs"

- name: Chown Hadoop to hadoop user
  file:
    path: "{{ hadoop_home }}"
    state: directory
    owner: hadoop
    group: hadoop
    recurse: yes
# NameNode - http://localhost:50070/
#
# ResourceManager - http://localhost:8088/
