---
# hadoop single node install: https://hadoop.apache.org/docs/r1.2.1/single_node_setup.html

- hosts: all
  vars:
    download_dir: /tmp/download
    share_dir: /usr/local/share

    atscale_version: 3.1.1.20
    atscale_download_file: "installer-offline-apache2_6-dev-{{ atscale_version }}.tar.gz"
    atscale_user: atscale
    atscale_home: /usr/local/atscale
    atscale_unpack_dir: /tmp/atscale_installer

    java_version: 1.8.0_71
    java_download_file: jdk-8u71-linux-x64.gz
    java_home: "{{ share_dir }}/jdk{{ java_version }}"

    hadoop_version: 2.6.3
    hadoop_download_file: "hadoop-{{ hadoop_version }}.tar.gz"
    hadoop_home: "{{ share_dir }}/hadoop-{{ hadoop_version }}"
    hadoop_conf_dir: "{{ hadoop_home }}/etc/hadoop"

    hive_version: 1.2.1
    hive_download_file: apache-hive-{{ hive_version }}-bin.tar.gz
    hive_home: "{{ share_dir }}/apache-hive-{{ hive_version }}-bin"
    hive_conf_dir: "{{ hive_home }}/conf"
    hive_lib_dir: "{{ hive_home }}/lib"

    impala_conf_dir: /etc/impala/conf

    mysql_hive_metastore_db: metastore
    mysql_hive_metastore_user: hive
    mysql_hive_metastore_password: hive

  tasks:
    - name: Create directories
      file:
        path: "{{ item }}"
        state: directory
        mode: 0755
      with_items:
        - "{{ download_dir }}"
        - "{{ share_dir }}"

    - name: Install packages
      include: install-packages.yml

    - name: Create users
      include: create-users.yml

    - name: Install Java
      include: "install-java.yml"

    - name: Install Hadoop
      include: "install-hadoop.yml"

    - name: Install Hive
      include: "install-hive.yml"

    - name: Install Impala
      include: "install-impala.yml"

    - name: Setup AtScale
      include: setup-atscale.yml

    - name: Clean up files & directories that are no longer needed
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /var/lib/apt/lists/
        - /var/tmp/
        - "{{ download_dir }}"

    - name: Drop docker-entrypoint.sh into place
      template:
        src: templates/bin/docker-entrypoint.sh.j2
        dest: /usr/local/bin/docker-entrypoint.sh
        mode: 0755
