---
# hadoop single node install: https://hadoop.apache.org/docs/r1.2.1/single_node_setup.html

- hosts: all
  vars: # use include_vars
  tasks:
    - name: include_vars common
      include_vars: vars/common.yml

    - name: include_vars for OS family Debian
      include_vars: vars/os_family_debian.yml
      when: ansible_os_family == 'Debian'

    - name: include_vars for OS family RedHat
      include_vars: vars/os_family_redhat.yml
      when: ansible_os_family == 'RedHat'

    - name: Create directories
      file:
        path: "{{ item }}"
        state: directory
        mode: 0755
      with_items:
        - "{{ download_dir }}"
        - "{{ share_dir }}"

    - name: Install packages
      include: tasks/install-packages.yml

    - name: Create users
      include: tasks/create-users.yml

    - name: Install Java
      include: tasks/install-java.yml

    - name: Install Hadoop
      include: tasks/install-hadoop.yml

    - name: Install Hive
      include: tasks/install-hive.yml

    - name: Install Impala
      include: tasks/install-impala.yml

    - name: Setup AtScale
      include: tasks/setup-atscale.yml

    - name: Clean up files & directories that are no longer needed
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /var/lib/apt/lists/
        - /var/tmp/
        - "{{ download_dir }}"

    - name: Drop docker-entrypoint.sh into place
      template:
        src: templates/bin/docker-entrypoint.sh.j2
        dest: /usr/local/bin/docker-entrypoint.sh
        mode: 0755
