---
# hadoop single node install: https://hadoop.apache.org/docs/r1.2.1/single_node_setup.html

- hosts: all
  vars:
    download_dir: /tmp/download
    share_dir: /usr/local/share

    java_version: 1.8.0_71
    java_download_file: jdk-8u71-linux-x64.gz
    java_home: "{{ share_dir }}/jdk{{ java_version }}"

    hadoop_version: 2.6.3
    hadoop_download_file: "hadoop-{{ hadoop_version }}.tar.gz"
    hadoop_home: "{{ share_dir }}/hadoop-{{ hadoop_version }}"
    hadoop_conf_dir: "{{ hadoop_home }}/etc/hadoop"


  tasks:
    - name: Create directories
      file:
        path: "{{ item }}"
        state: directory
        mode: 0755
      with_items:
        - "{{ download_dir }}"
        - "{{ share_dir }}"


    - name: use apt
      include: use-apt.yml

    - name: create users
      include: create-users.yml


    - name: install-java
      include: "install-java.yml"

    - name: install-hadoop
      include: "install-hadoop.yml"



    - name: Clean up files & directories that are no longer needed
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /var/lib/apt/lists/
        - /var/tmp/
        - "{{ download_dir }}"

    - name: Drop docker-entrypoint.sh into place
      template:
        src: templates/bin/docker-entrypoint.sh.j2
        dest: /usr/local/bin/docker-entrypoint.sh
        mode: 0755

####
## TODO
####
# script to fire up hadoop & friends
# ssh has to be running when node comes up
# configure for pseudo-distributed operation




# environment:
#   PATH: "{{ ansible_env.PATH }}:/thingy/bin"
#   JAVA_HOME: /usr/java/jre1.8.0_51
