---
- name: Download Java Checksum
  get_url:
    url: "http://artifactory.corp.atscale.com/ext-packages/java/{{ java_download_file }}.md5"
    dest: "{{ download_dir }}/{{ java_download_file }}.md5"
    force: yes
    mode: 0440

- name: Download Java
  get_url:
    url: "http://artifactory.corp.atscale.com/ext-packages/java/{{ java_download_file }}"
    # TODO: put this back in once EPEL gets Ansible 2.x
    # checksum: "md5:{{ lookup('file', '{{ download_dir }}/{{ java_download_file }}.md5') }}"
    dest: "{{ download_dir }}/{{ java_download_file }}"
    timeout: 60
    mode: 0440

- name: Unpack Java
  unarchive:
    src: "{{ download_dir }}/{{ java_download_file }}"
    copy: no
    dest: "{{ share_dir }}"
