---
download_dir: /tmp/download
share_dir: /usr/local/share

atscale_version: 3.2.1.61
atscale_flavor: "-dev"
atscale_download_file: "installer-offline-{{ atscale_version }}{{ atscale_flavor }}.tar.gz"
atscale_user: atscale
atscale_home: /usr/local/atscale
atscale_installer_dir: /tmp/atscale_installer
atscale_installer_unpack_dir: "{{ atscale_installer_dir }}/package"
atscale_host_name: docker.local

java_version: 1.8.0_71
java_download_file: jdk-8u71-linux-x64.gz
java_home: "{{ share_dir }}/jdk{{ java_version }}"

hadoop_version: 2.6.3
hadoop_download_file: "hadoop-{{ hadoop_version }}.tar.gz"
hadoop_home: "{{ share_dir }}/hadoop-{{ hadoop_version }}"
hadoop_conf_dir: "{{ hadoop_home }}/etc/hadoop"

hive_version: 1.2.1
hive_download_file: apache-hive-{{ hive_version }}-bin.tar.gz
hive_home: "{{ share_dir }}/apache-hive-{{ hive_version }}-bin"
hive_conf_dir: "{{ hive_home }}/conf"
hive_lib_dir: "{{ hive_home }}/lib"

impala_conf_dir: /etc/impala/conf

mysql_hive_metastore_db: metastore
mysql_hive_metastore_user: hive
mysql_hive_metastore_password: hive
